var prods = [
	{
	  sku: "ACR301",
	  category: "accessories",
	  productTitle: "Color Pop Earbuds",
	  productUpperDescription: " ",
	  productLowerDescription: "Use with any standard audio device.  The Color Pop earbuds come with interchangeable soft rubber earbud covers.  The earbuds also come equipped with a clear, plastic case for easy cable storage.",
	  printingOptions: "Product Size: 0.75\” x 2.75\”<br/>Imprint Size: 1.5\" x 1.5\"<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print",
	  techSpecifications: "3.5mm Audio Jack<br/>46-inch earbud Cable<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/accessory/COLORPOP1.jpg",
	  computerSlide2: "../images/accessory/COLORPOP3.jpg",
	  tabletSlide1: "../images/accessory/COLORPOP1.jpg",
	  tabletSlide2: "../images/accessory/COLORPOP3.jpg",
	  mobileSlide1: "../images/accessory/COLORPOP1.jpg",
	  mobileSlide2: "../images/accessory/COLORPOP3.jpg",
	},
	{
	  sku: "ACR302",
	  category: "accessories",
	  productTitle: "Rebel Earbuds",
	  productUpperDescription: " ",
	  productLowerDescription: "Use with any standard audio device.  The Rebel earbuds come with a triangle plastic case for easy cable storage.",
	  printingOptions: "Product Size: 0.75\” x 2.5\”<br/>Imprint Size: 1.31\" x 1.31\"<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print",
	  techSpecifications: "3.5mm Audio Jack<br/>46-inch earbud Cable<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/accessory/REBEL1.jpg",
	  computerSlide2: "../images/accessory/REBEL3.jpg",
	  tabletSlide1: "../images/accessory/REBEL1.jpg",
	  tabletSlide2: "../images/accessory/REBEL3.jpg",
	  mobileSlide1: "../images/accessory/REBEL1.jpg",
	  mobileSlide2: "../images/accessory/REBEL3.jpg",
	},
	{
	  sku: "ACR303",
	  category: "accessories",
	  productTitle: "Auto Charger",
	  productUpperDescription: " ",
	  productLowerDescription: "The Auto Charger is a plug-in adapter. Plug into any accessory power outlet to charge personal devices. The charger has an LED indicator light to show when power is connected. It is compatible with smartphones and any device that provides USB cable for charging (excluding iPad® and tablet devices).",
	  printingOptions: "Product Size: 2.25\” x 2.75\”<br/>Imprint Size: 0.38\" x 0.88\"<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print",
	  techSpecifications: "3.5mm Audio Jack<br/>46-inch earbud Cable<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/accessory/DP-Accessories-AutoAdapter.jpg",
	  computerSlide2: "../images/accessory/DP-Accessories-AutoAdapter2.jpg",
	  computerSlide3: "../images/accessory/DP-Accessories-AutoAdapter3.jpg",
	  tabletSlide1: "../images/accessory/DP-Accessories-AutoAdapter.jpg",
	  tabletSlide2: "../images/accessory/DP-Accessories-AutoAdapter2.jpg",
	  tabletSlide3: "../images/accessory/DP-Accessories-AutoAdapter3.jpg",
	  mobileSlide1: "../images/accessory/DP-Accessories-AutoAdapter.jpg",
	  mobileSlide2: "../images/accessory/DP-Accessories-AutoAdapter2.jpg",
	  mobileSlide3: "../images/accessory/DP-Accessories-AutoAdapter3.jpg",	  
	},
	{
	  sku: "ACR304",
	  category: "cases",
	  productTitle: "Compact Carrying Case",
	  productUpperDescription: " ",
	  productLowerDescription: "Full-zip compact case features faux leather material.",
	  printingOptions: "Product Size: 2.5\” x 4.5\” x 1.5\"<br/>Imprint Size:<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print",
	  techSpecifications: "",
	  computerSlide1: "../images/products/cases/Packaging-Case1-1.jpg",
	  computerSlide2: "../images/products/cases/Packaging-Case1-2.jpg",
	  computerSlide3: "../images/products/cases/Packaging-Case1-3.jpg",
	  computerSlide4: "../images/products/cases/Packaging-Case1-4.jpg",	  
	  tabletSlide1: "../images/products/cases/Packaging-Case1-1.jpg",
	  tabletSlide2: "../images/products/cases/Packaging-Case1-2.jpg",
	  tabletSlide3: "../images/products/cases/Packaging-Case1-3.jpg",
	  tabletSlide4: "../images/products/cases/Packaging-Case1-4.jpg",	  
	  mobileSlide1: "../images/products/cases/Packaging-Case1-1.jpg",
	  mobileSlide2: "../images/products/cases/Packaging-Case1-2.jpg",
	  mobileSlide3: "../images/products/cases/Packaging-Case1-3.jpg",
	  mobileSlide4: "../images/products/cases/Packaging-Case1-4.jpg",	  
	},
	{
	  sku: "ACR305",
	  category: "cases",
	  productTitle: "Classic Carrying Case",
	  productUpperDescription: " ",
	  productLowerDescription: "Full-zip compact case features faux leather material.",
	  printingOptions: "Product Size: 4\” x 5\” x 2\"<br/>Imprint Size:<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print",
	  techSpecifications: "",
	  computerSlide1: "../images/products/cases/Packaging-Case2-1.jpg",
	  computerSlide2: "../images/products/cases/Packaging-Case2-2.jpg",
	  computerSlide3: "../images/products/cases/Packaging-Case2-3.jpg",
	  computerSlide4: "../images/products/cases/Packaging-Case2-4.jpg",	  
	  tabletSlide1: "../images/products/cases/Packaging-Case2-1.jpg",
	  tabletSlide2: "../images/products/cases/Packaging-Case2-2.jpg",
	  tabletSlide3: "../images/products/cases/Packaging-Case2-3.jpg",
	  tabletSlide4: "../images/products/cases/Packaging-Case2-4.jpg",	  
	  mobileSlide1: "../images/products/cases/Packaging-Case2-1.jpg",
	  mobileSlide2: "../images/products/cases/Packaging-Case2-2.jpg",
	  mobileSlide3: "../images/products/cases/Packaging-Case2-3.jpg",
	  mobileSlide4: "../images/products/cases/Packaging-Case2-4.jpg",	  
	},
	{
	  sku: "ACR306",
	  category: "cases",
	  productTitle: "Premium Carrying Case",
	  productUpperDescription: " ",
	  productLowerDescription: "Full-zip compact case features faux leather material.",
	  printingOptions: "Product Size: 4\” x 6.5\” x 1.25\"<br/>Imprint Size:<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print",
	  techSpecifications: "",
	  computerSlide1: "../images/products/cases/Packaging-Case3-1.jpg",
	  computerSlide2: "../images/products/cases/Packaging-Case3-2.jpg",
	  computerSlide3: "../images/products/cases/Packaging-Case3-3.jpg",
	  computerSlide4: "../images/products/cases/Packaging-Case3-4.jpg",	  
	  tabletSlide1: "../images/products/cases/Packaging-Case3-1.jpg",
	  tabletSlide2: "../images/products/cases/Packaging-Case3-2.jpg",
	  tabletSlide3: "../images/products/cases/Packaging-Case3-3.jpg",
	  tabletSlide4: "../images/products/cases/Packaging-Case3-4.jpg",	  
	  mobileSlide1: "../images/products/cases/Packaging-Case3-1.jpg",
	  mobileSlide2: "../images/products/cases/Packaging-Case3-2.jpg",
	  mobileSlide3: "../images/products/cases/Packaging-Case3-3.jpg",
	  mobileSlide4: "../images/products/cases/Packaging-Case3-4.jpg",	  
	},
	{
	  sku: "ACR307",
	  category: "cases",
	  productTitle: "Premium Box",
	  productUpperDescription: " ",
	  productLowerDescription: "Cardboard gear box features styrofoam insert to keep your tech safe and snug.",
	  printingOptions: "Product Size: 4\” x 6.5\” x 1.25\"<br/>Imprint Size:<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print",
	  techSpecifications: "",
	  computerSlide1: "../images/products/cases/Packaging-Case4-1.jpg",
	  computerSlide2: "../images/products/cases/Packaging-Case4-2.jpg",
	  computerSlide3: "../images/products/cases/Packaging-Case4-3.jpg",  
	  tabletSlide1: "../images/products/cases/Packaging-Case4-1.jpg",
	  tabletSlide2: "../images/products/cases/Packaging-Case4-2.jpg",
	  tabletSlide3: "../images/products/cases/Packaging-Case4-3.jpg",	  
	  mobileSlide1: "../images/products/cases/Packaging-Case4-1.jpg",
	  mobileSlide2: "../images/products/cases/Packaging-Case4-2.jpg",
	  mobileSlide3: "../images/products/cases/Packaging-Case4-3.jpg",  
	},
	{
	  sku: "ACR308",
	  category: "cases",
	  productTitle: "Standard Box",
	  productUpperDescription: " ",
	  productLowerDescription: "Standard individual Power Bank packaging. Cardboard box keeps all your tech together",
	  printingOptions: "Product Size: 2.25\” x 4.875\” x 1.25\"<br/>Imprint Size:<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print",
	  techSpecifications: "",
	  computerSlide1: "../images/products/cases/Packaging-Case5-1.jpg",
	  computerSlide2: "../images/products/cases/Packaging-Case5-2.jpg",
	  computerSlide3: "../images/products/cases/Packaging-Case5-3.jpg",  
	  tabletSlide1: "../images/products/cases/Packaging-Case5-1.jpg",
	  tabletSlide2: "../images/products/cases/Packaging-Case5-2.jpg",
	  tabletSlide3: "../images/products/cases/Packaging-Case5-3.jpg",	  
	  mobileSlide1: "../images/products/cases/Packaging-Case5-1.jpg",
	  mobileSlide2: "../images/products/cases/Packaging-Case5-2.jpg",
	  mobileSlide3: "../images/products/cases/Packaging-Case5-3.jpg",  
	},
	{
	  sku: "ACR309",
	  category: "flashdrives",
	  productTitle: "Atlantic",
	  productUpperDescription: " ",
	  productLowerDescription: "The Atlantic is the most popular USB on the market.  It is small, durable and includes an accessory loop so you can add a lanyard or keychain.  With an industry-leading imprint method, we use the maximum area to expose your logo across the entire drive.  We can match the body and even swivel of this USB to match your logo exactly. Always in stock, we guarantee that your Atlantic USB Drive will be delivered on or before your requested date.",
	  printingOptions: "Product Size: 2.2\” x 0.6\”<br/>Imprint Size: 1\" x 0.5\"<br/>Imprint locations: 2 locations<br/>Decorating Methods: Screen Print, 4 Color Process, Laser Engrave",
	  techSpecifications: "Speed: 2.0 USB<br/>Available Memory: 64MB, 128MB, 256MB, 512MB, 1GB, 2GB, 4GB, 8GB, 16GB, 32GB, 64GB<br/>Memory Type: Grade A, Tier 1<br/>Optional Services: Data Pre-load<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/flashdrives/07.jpg",
	  computerSlide2: "../images/products/flashdrives/DSCF1105.jpg",
	  computerSlide3: "../images/products/flashdrives/DSCF1112.jpg",
	  tabletSlide1: "../images/products/flashdrives/07.jpg",
	  tabletSlide2: "../images/products/flashdrives/DSCF1105.jpg",
	  tabletSlide3: "../images/products/flashdrives/DSCF1112.jpg",
	  mobileSlide1: "../images/products/flashdrives/07.jpg",
	  mobileSlide2: "../images/products/flashdrives/DSCF1105.jpg",
	  mobileSlide3: "../images/products/flashdrives/DSCF1112.jpg",
	},
	{
	  sku: "ACR310",
	  category: "flashdrives",
	  productTitle: "Caspian",
	  productUpperDescription: " ",
	  productLowerDescription: "The Caspian USB Flash Drive offers a sleek silver center and a colored edge. It will give your brand and logo a memorable appearance. Available in any color, the Caspian Style USB Drive is certain to be a success during your next promotion.",
	  printingOptions: "Product Size: 2.5\” x 0.9\”<br/>Imprint Size: 1\" x 0.5\"<br/>Imprint locations: 2 locations<br/>Decorating Methods: Screen Print, 4 Color Process, Laser Engrave",
	  techSpecifications: "Speed: 2.0 USB<br/>Available Memory: 64MB, 128MB, 256MB, 512MB, 1GB, 2GB, 4GB, 8GB, 16GB, 32GB, 64GB<br/>Memory Type: Grade A, Tier 1<br/>Optional Services: Data Pre-load<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/flashdrives/MIAMI1.jpg",
	  computerSlide2: "../images/products/flashdrives/MIAMI3.jpg",
	  computerSlide3: "../images/products/flashdrives/MIAMI4.jpg",
	  tabletSlide1: "../images/products/flashdrives/MIAMI1.jpg",
	  tabletSlide2: "../images/products/flashdrives/MIAMI3.jpg",
	  tabletSlide3: "../images/products/flashdrives/MIAMI4.jpg",
	  mobileSlide1: "../images/products/flashdrives/MIAMI1.jpg",
	  mobileSlide2: "../images/products/flashdrives/MIAMI3.jpg",
	  mobileSlide3: "../images/products/flashdrives/MIAMI4.jpg",
	},
	{
	  sku: "ACR311",
	  category: "flashdrives",
	  productTitle: "Nile",
	  productUpperDescription: " ",
	  productLowerDescription: "The Nile USB Flash Drive offers a sleek silver center and a colored edge. One of our bestsellers, it will give your brand a memorable appearance. Available in any color, the Chicago Style USB Drive is certain to reflect your logo in a way you never thought imaginable.",
	  printingOptions: "Product Size: 2.5\” x 0.9\”<br/>Imprint Size: 1\" x 0.5\"<br/>Imprint locations: 2 locations<br/>Decorating Methods: Screen Print, 4 Color Process, Laser Engrave",
	  techSpecifications: "Speed: 2.0 USB<br/>Available Memory: 64MB, 128MB, 256MB, 512MB, 1GB, 2GB, 4GB, 8GB, 16GB, 32GB, 64GB<br/>Memory Type: Grade A, Tier 1<br/>Optional Services: Data Pre-load<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/flashdrives/CHICAGO1.jpg",
	  computerSlide2: "../images/products/flashdrives/CHICAGO3.jpg",
	  computerSlide3: "../images/products/flashdrives/CHICAGO4.jpg",
	  tabletSlide1: "../images/products/flashdrives/CHICAGO1.jpg",
	  tabletSlide2: "../images/products/flashdrives/CHICAGO3.jpg",
	  tabletSlide3: "../images/products/flashdrives/CHICAGO4.jpg",
	  mobileSlide1: "../images/products/flashdrives/CHICAGO1.jpg",
	  mobileSlide2: "../images/products/flashdrives/CHICAGO3.jpg",
	  mobileSlide3: "../images/products/flashdrives/CHICAGO4.jpg",
	},
	{
	  sku: "ACR312",
	  category: "flashdrives",
	  productTitle: "Huron",
	  productUpperDescription: " ",
	  productLowerDescription: "The Huron is not your traditional USB flash drive.  Made from metal and disguised as a key, hang your logo and brand on your keychain and take it with you on the go.  An excellent addition to any trade show, event or outing.  ",
	  printingOptions: "Product Size: 1\” x 2.25\”<br/>Imprint Size: 1.5\" x 0.38\"<br/>Imprint locations: 2 locations<br/>Decorating Methods: Screen Print, Laser Engrave",
	  techSpecifications: "Speed: 2.0 USB<br/>Available Memory: 64MB, 128MB, 256MB, 512MB, 1GB, 2GB, 4GB, 8GB, 16GB, 32GB, 64GB<br/>Memory Type: Grade A, Tier 1<br/>Optional Services: Data Pre-load<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/flashdrives/HURON1.jpg",
	  computerSlide2: "../images/products/flashdrives/HURON2.jpg",
	  computerSlide3: "../images/products/flashdrives/HURON3.jpg",
	  tabletSlide1: "../images/products/flashdrives/HURON1.jpg",
	  tabletSlide2: "../images/products/flashdrives/HURON2.jpg",
	  tabletSlide3: "../images/products/flashdrives/HURON3.jpg",
	  mobileSlide1: "../images/products/flashdrives/HURON1.jpg",
	  mobileSlide2: "../images/products/flashdrives/HURON2.jpg",
	  mobileSlide3: "../images/products/flashdrives/HURON3.jpg",
	},
	{
	  sku: "ACR313",
	  category: "flashdrives",
	  productTitle: "Pacific",
	  productUpperDescription: " ",
	  productLowerDescription: "Among our bestselling USB Flash Drives, the Pacific Style USB Drive has a large imprint area, comes in many colors and is quickly customizable to deliver your product on time and under budget. Have a custom Pantone Color? Ask us to match the USB drive to fit your brand entirely! The Pacific USB Flash Drive is a fantastic giveaway for your next promotion.",
	  printingOptions: "Product Size: 2.8\” x 0.8\”<br/>Imprint Size: 1\" x 0.5\"<br/>Imprint locations: 2 locations<br/>Decorating Methods: Screen Print, 4 Color Process",
	  techSpecifications: "Speed: 2.0 USB<br/>Available Memory: 64MB, 128MB, 256MB, 512MB, 1GB, 2GB, 4GB, 8GB, 16GB, 32GB, 64GB<br/>Memory Type: Grade A, Tier 1<br/>Optional Services: Data Pre-load<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/flashdrives/DSCF1169.jpg",
	  computerSlide2: "../images/products/flashdrives/DSCF1173.jpg",
	  computerSlide3: "../images/products/flashdrives/DSCF1178.jpg",
	  tabletSlide1: "../images/products/flashdrives/DSCF1169.jpg",
	  tabletSlide2: "../images/products/flashdrives/DSCF1173.jpg",
	  tabletSlide3: "../images/products/flashdrives/DSCF1178.jpg",
	  mobileSlide1: "../images/products/flashdrives/DSCF1169.jpg",
	  mobileSlide2: "../images/products/flashdrives/DSCF1173.jpg",
	  mobileSlide3: "../images/products/flashdrives/DSCF1178.jpg",
	},
	{
	  sku: "ACR314",
	  category: "flashdrives",
	  productTitle: "Placid",
	  productUpperDescription: " ",
	  productLowerDescription: "Looking to make a statement with your next promotion?  Then the Placid USB is for you.  This thin and light USB fits perfectly into your wallet.  It can hold up to 64GB of data and with a 4-Color Processed logo on both the front and back location.  Your branded Placid USB will be the talk of the town.",
	  printingOptions: "Product Size: 2.49\” x 3.4\”<br/>Imprint Size: 2.49\" x 3.4\"<br/>Imprint locations: 2 locations<br/>Decorating Methods: Screen Print, 4 Color Process",
	  techSpecifications: "Speed: 2.0 USB<br/>Available Memory: 64MB, 128MB, 256MB, 512MB, 1GB, 2GB, 4GB, 8GB, 16GB, 32GB, 64GB<br/>Memory Type: Grade A, Tier 1<br/>Optional Services: Data Pre-load<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/flashdrives/PORTLAND_1.jpg",
	  computerSlide2: "../images/products/flashdrives/PORTLAND_2.jpg",
	  computerSlide3: "../images/products/flashdrives/PORTLAND_3.jpg",
	  tabletSlide1: "../images/products/flashdrives/PORTLAND_1.jpg",
	  tabletSlide2: "../images/products/flashdrives/PORTLAND_2.jpg",
	  tabletSlide3: "../images/products/flashdrives/PORTLAND_3.jpg",
	  mobileSlide1: "../images/products/flashdrives/PORTLAND_1.jpg",
	  mobileSlide2: "../images/products/flashdrives/PORTLAND_2.jpg",
	  mobileSlide3: "../images/products/flashdrives/PORTLAND_3.jpg",
	},
	{
	  sku: "ACR315",
	  category: "flashdrives",
	  productTitle: "Gulf",
	  productUpperDescription: " ",
	  productLowerDescription: "The Gulf USB Flash Drive converts into a standard wristband that can be worn around town.  It comes in any color and can fit large logos due to its massive imprint area. Perfect for educational, finance, or business giveaways, the Gulf USB Flash Drive is a unique gift for your next event. ",
	  printingOptions: "Product Size: 8.5\” x 7.5\”<br/>Imprint Size: 4.4\" x 0.5\"<br/>Imprint locations: 2 locations<br/>Decorating Methods: Screen Print, 4 Color Process, Laser Engrave",
	  techSpecifications: "Speed: 2.0 USB<br/>Available Memory: 64MB, 128MB, 256MB, 512MB, 1GB, 2GB, 4GB, 8GB, 16GB, 32GB, 64GB<br/>Memory Type: Grade A, Tier 1<br/>Optional Services: Data Pre-load<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/flashdrives/DSCF7157.jpg",
	  computerSlide2: "../images/products/flashdrives/DSCF7155.jpg",
	  tabletSlide1: "../images/products/flashdrives/DSCF7157.jpg",
	  tabletSlide2: "../images/products/flashdrives/DSCF7155.jpg",
	  mobileSlide1: "../images/products/flashdrives/DSCF7157.jpg",
	  mobileSlide2: "../images/products/flashdrives/DSCF7155.jpg",
	},
	{
	  sku: "ACR316",
	  category: "flashdrives",
	  productTitle: "Custom USB",
	  productUpperDescription: " ",
	  productLowerDescription: "A fully custom USB Flash Drive is the ultimate in Branded Memory Products. If you are looking for a piece that will WOW, this is it.  Let us transform your logo, product or idea into a reality using our proprietary 3D molding technology. Ask your dedicated Account Executive how a Custom Shape Flash Drive will change your next promotion.",
	  printingOptions: "Product Size: 8.5\” x 7.5\”<br/>Imprint Size: 4.4\" x 0.5\"<br/>Imprint locations: 2 locations<br/>Decorating Methods: Screen Print, 4 Color Process, Laser Engrave",
	  techSpecifications: "Speed: 2.0 USB<br/>Available Memory: 64MB, 128MB, 256MB, 512MB, 1GB, 2GB, 4GB, 8GB, 16GB, 32GB, 64GB<br/>Memory Type: Grade A, Tier 1<br/>Optional Services: Data Pre-load<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/flashdrives/07.jpg",
	  computerSlide2: "../images/products/flashdrives/DSCF1105.jpg",
	  tabletSlide1: "../images/products/flashdrives/CUSTOM1.jpg",
	  tabletSlide2: "../images/products/flashdrives/CUSTOM2.jpg",
	  mobileSlide1: "../images/products/flashdrives/CUSTOM1jpg",
	  mobileSlide2: "../images/products/flashdrives/CUSTOM2.jpg",
	},
	{
	  sku: "ACR317",
	  category: "kits",
	  productTitle: "Premium set #1",
	  productUpperDescription: " ",
	  productLowerDescription: "Set includes:Compact carrying case. Charging cable. Power bank (your choice of Washington, Adams, Jefferson or Monroe)",
	  printingOptions: "Product Size:<br/>Imprint Size:<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print",
	  techSpecifications: "",
	  computerSlide1: "../images/products/kits/DP-PremiumSet-1_1.jpg",
	  computerSlide2: "../images/products/kits/DP-PremiumSet-1_2.jpg",
	  computerSlide3: "../images/products/kits/DP-PremiumSet-1_3.jpg",  
	  tabletSlide1: "../images/products/kits/DP-PremiumSet-1_1.jpg",
	  tabletSlide2: "../images/products/kits/DP-PremiumSet-1_2.jpg",
	  tabletSlide3: "../images/products/kits/DP-PremiumSet-1_3.jpg",  
	  mobileSlide1: "../images/products/kits/DP-PremiumSet-1_1.jpg",
	  mobileSlide2: "../images/products/kits/DP-PremiumSet-1_2.jpg",
	  mobileSlide3: "../images/products/kits/DP-PremiumSet-1_3.jpg",
	},
	{
	  sku: "ACR318",
	  category: "kits",
	  productTitle: "Premium set #2",
	  productUpperDescription: " ",
	  productLowerDescription: "Set includes:Classic carrying case. Mini auto charger. Rebel earbuds (case not included.) Power bank of your choice!",
	  printingOptions: "Product Size:<br/>Imprint Size:<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print",
	  techSpecifications: "",
	  computerSlide1: "../images/products/kits/DP-PremiumSet-2_1.jpg",
	  computerSlide2: "../images/products/kits/DP-PremiumSet-2_2.jpg",
	  computerSlide3: "../images/products/kits/DP-PremiumSet-2_3.jpg",  
	  tabletSlide1: "../images/products/kits/DP-PremiumSet-2_1.jpg",
	  tabletSlide2: "../images/products/kits/DP-PremiumSet-2_2.jpg",
	  tabletSlide3: "../images/products/kits/DP-PremiumSet-2_3.jpg",  
	  mobileSlide1: "../images/products/kits/DP-PremiumSet-2_1.jpg",
	  mobileSlide2: "../images/products/kits/DP-PremiumSet-2_2.jpg",
	  mobileSlide3: "../images/products/kits/DP-PremiumSet-2_3.jpg",
	},
	{
	  sku: "ACR319",
	  category: "kits",
	  productTitle: "Premium set #3",
	  productUpperDescription: " ",
	  productLowerDescription: "Premium carrying case. Mini auto charger. Wall adapter. Charging cable. Your choice of power bank!",
	  printingOptions: "Product Size:<br/>Imprint Size:<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print",
	  techSpecifications: "",
	  computerSlide1: "../images/products/kits/DP-PremiumSet-3_1.jpg",
	  computerSlide2: "../images/products/kits/DP-PremiumSet-3_2.jpg",
	  computerSlide3: "../images/products/kits/DP-PremiumSet-3_3.jpg",  
	  tabletSlide1: "../images/products/kits/DP-PremiumSet-3_1.jpg",
	  tabletSlide2: "../images/products/kits/DP-PremiumSet-3_2.jpg",
	  tabletSlide3: "../images/products/kits/DP-PremiumSet-3_3.jpg",  
	  mobileSlide1: "../images/products/kits/DP-PremiumSet-3_1.jpg",
	  mobileSlide2: "../images/products/kits/DP-PremiumSet-3_2.jpg",
	  mobileSlide3: "../images/products/kits/DP-PremiumSet-3_3.jpg",
	},
	{
	  sku: "ACR320",
	  category: "kits",
	  productTitle: "Premium set #4",
	  productUpperDescription: " ",
	  productLowerDescription: "Premium gear box. Cylinder Bluetooth speaker. Charging cable. Your choice of power bank!",
	  printingOptions: "Product Size:<br/>Imprint Size:<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print",
	  techSpecifications: "",
	  computerSlide1: "../images/products/kits/DP-PremiumSet-4_1.jpg",
	  computerSlide2: "../images/products/kits/DP-PremiumSet-4_2.jpg",
	  computerSlide3: "../images/products/kits/DP-PremiumSet-4_3.jpg",  
	  tabletSlide1: "../images/products/kits/DP-PremiumSet-4_1.jpg",
	  tabletSlide2: "../images/products/kits/DP-PremiumSet-4_2.jpg",
	  tabletSlide3: "../images/products/kits/DP-PremiumSet-4_3.jpg",  
	  mobileSlide1: "../images/products/kits/DP-PremiumSet-4_1.jpg",
	  mobileSlide2: "../images/products/kits/DP-PremiumSet-4_2.jpg",
	  mobileSlide3: "../images/products/kits/DP-PremiumSet-4_3.jpg",
	},
	{
	  sku: "ACR321",
	  category: "powerbanks",
	  productTitle: "Washington",
	  productUpperDescription: " ",
	  productLowerDescription: "The sleek surface allows for your logo to be branded directly on the power bank.  This custom item allows for any type of branding and customization.  If you are looking for bulk quantities of the most popular portable power bank out there, the Washington is your answer.",
	  printingOptions: "Product Size: 3.6\” x 1\” x 1\"<br/>Imprint Size: Imprint Size: 2.6\" x 0.5\"<br/>Imprint locations: 4 locations<br/>Decorating Methods: Screen Print, 4-Color Process, Laser Engrave",
	  techSpecifications: "mAh: 2200, 2600, 3000<br/> # of Outputs: 1<br/>Output Current: 5V-1000ma<br/> Input Current: 5V-1000ma<br/>Standby Time: 60 days<br/>Battery Type: Grade A, Lithium Ion<br/>Charging Time: 1.5-Hours <br/>Works on iPhones, Androids, Blackberrys and other phones that require a USB charging cord.<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/powerbanks/DSC_2157.jpg",
	  computerSlide2: "../images/products/powerbanks/ms-3.jpg",
	  computerSlide3: "../images/products/powerbanks/DSC_2332.jpg",
	  tabletSlide1: "../images/products/powerbanks/DSC_2157.jpg",
	  tabletSlide2: "../images/products/powerbanks/ms-3.jpg",
	  tabletSlide3: "../images/products/powerbanks/DSC_2332.jpg",
	  mobileSlide1: "../images/products/powerbanks/DSC_2157.jpg",
	  mobileSlide2: "../images/products/powerbanks/ms-3.jpg",
	  mobileSlide3: "../images/products/powerbanks/DSC_2332.jpg",
	},
	{
	  sku: "ACR322",
	  category: "powerbanks",
	  productTitle: "Adams",
	  productUpperDescription: " ",
	  productLowerDescription: "The Adams power bank is plastic power bank USB charger that allows for full customization. The Adams will allow you to emphasize your logo and promote your brand the way you desire, from custom PMS color imprints or casing colors.",
	  printingOptions: "Product Size: 3.6\” x 1\” x 1\"<br/>Imprint Size: 2.15\" x 0.5\"<br/>Imprint locations: 4 locations<br/>Decorating Methods: Screen Print, 4 Color Process, Laser Engrave, Full Custom Wrap",
	  techSpecifications: "mAh: 2200, 2600, 3000<br/> # of Outputs: 1<br/>Output Current: 5V-1000ma<br/> Input Current: 5V-1000ma<br/>Standby Time: 60 days<br/>Battery Type: Grade A, Lithium Ion<br/>Charging Time: 1.5-Hours <br/>Works on iPhones, Androids, Blackberrys and other phones that require a USB charging cord.<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/powerbanks/DSC_2159.jpg",
	  computerSlide2: "../images/products/powerbanks/DSC_2302.jpg",
	  computerSlide3: "../images/products/powerbanks/DSC_2303.jpg",
	  computerSlide4: "../images/products/powerbanks/DSC_2335.jpg",
	  tabletSlide1: "../images/products/powerbanks/DSC_2159.jpg",
	  tabletSlide2: "../images/products/powerbanks/DSC_2302.jpg",
	  tabletSlide3: "../images/products/powerbanks/DSC_2303.jpg",
	  tabletSlide4: "../images/products/powerbanks/DSC_2335.jpg",
	  mobileSlide1: "../images/products/powerbanks/DSC_2159.jpg",
	  mobileSlide2: "../images/products/powerbanks/DSC_2302.jpg",
	  mobileSlide3: "../images/products/powerbanks/DSC_2303.jpg",
	  mobileSlide4: "../images/products/powerbanks/DSC_2335.jpg",
	},
	{
	  sku: "ACR323",
	  category: "powerbanks",
	  productTitle: "Jefferson",
	  productUpperDescription: " ",
	  productLowerDescription: "The Jefferson power bank is the most economical custom power bank.  Made from plastic, it is extremely durable and great for corporate events, school functions and gifts.  It comes with a lanyard and key loop attached, so you can simply attach it to your keychain and bring your branded logo with you wherever you go.",
	  printingOptions: "Product Size: 3.75\” x 1\” x 1\"<br/>Imprint area: 2.15\" x 0.5\"<br/>Imprint locations: 4 locations<br/>Decorating Methods: Screen Print, 4 Color Process, Laser Engrave",
	  techSpecifications: "mAh: 2200, 2600, 3000<br/> # of Outputs: 1<br/>Output Current: 5V-1000ma<br/> Input Current: 5V-1000ma<br/>Standby Time: 60 days<br/>Battery Type: Grade A, Lithium Ion<br/>Charging Time: 1.5-Hours <br/>Works on iPhones, Androids, Blackberrys and other phones that require a USB charging cord.<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/powerbanks/DSC_2161.jpg",
	  computerSlide2: "../images/products/powerbanks/DSC_2301.jpg",
	  computerSlide3: "../images/products/powerbanks/DSC_2336.jpg",
	  computerSlide4: "../images/products/powerbanks/DSC_2299.jpg",
	  tabletSlide1: "../images/products/powerbanks/DSC_2161.jpg",
	  tabletSlide2: "../images/products/powerbanks/DSC_2301.jpg",
	  tabletSlide3: "../images/products/powerbanks/DSC_2336.jpg",
	  tabletSlide4: "../images/products/powerbanks/DSC_2299.jpg",
	  mobileSlide1: "../images/products/powerbanks/DSC_2161.jpg",
	  mobileSlide2: "../images/products/powerbanks/DSC_2301.jpg",
	  mobileSlide3: "../images/products/powerbanks/DSC_2336.jpg",
	  mobileSlide4: "../images/products/powerbanks/DSC_2299.jpg",
	},
	{
	  sku: "ACR324",
	  category: "powerbanks",
	  productTitle: "Kennedy",
	  productUpperDescription: " ",
	  productLowerDescription: "The Kennedy is a metal power bank that also includes a flashlight.  With a massive imprint area, you can drop almost any imprint or logo on the power bank.  Take advantage of the multiple sided imprint areas and customize your charger even further.",
	  printingOptions: "Product Size: 2.25\” x 4.063\” x 0.375\"<br/>Imprint area: 3\" x 1.5\"<br/>Imprint locations: 2 locations<br/>Decorating Methods: Screen Print, 4 Color Process",
	  techSpecifications: "mAh: 2200, 2600, 3000<br/> # of Outputs: 1<br/>Output Current: 5V-1000ma<br/> Input Current: 5V-1000ma<br/>Standby Time: 60 days<br/>Battery Type: Grade A, Lithium Ion<br/>Charging Time: 1.5-Hours <br/>Works on iPhones, Androids, Blackberrys and other phones that require a USB charging cord.<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/powerbanks/DSC_2169_2.jpg",
	  computerSlide2: "../images/products/powerbanks/DSC_2169.jpg",
	  computerSlide3: "../images/products/powerbanks/Kennedy.jpg",
	  computerSlide4: "../images/products/powerbanks/DSC_2298.jpg",
	  tabletSlide1: "../images/products/powerbanks/DSC_2169_2.jpg",
	  tabletSlide2: "../images/products/powerbanks/DSC_2169.jpg",
	  tabletSlide3: "../images/products/powerbanks/Kennedy.jpg",
	  tabletSlide4: "../images/products/powerbanks/DSC_2298.jpg",
	  mobileSlide1: "../images/products/powerbanks/DSC_2169_2.jpg",
	  mobileSlide2: "../images/products/powerbanks/DSC_2169.jpg",
	  mobileSlide3: "../images/products/powerbanks/Kennedy.jpg",
	  mobileSlide4: "../images/products/powerbanks/DSC_2298.jpg",
	},
	{
	  sku: "ACR325",
	  category: "powerbanks",
	  productTitle: "Roosevelt",
	  productUpperDescription: " ",
	  productLowerDescription: "The Roosevelt model is a metal power bank with a flashlight feature.  The sleek surface allows for your logo to be branded directly on the power bank which looks amazing.  This item also allows for any type of branding and customization on all four sides.",
	  printingOptions: "Product Size: 3.6\” x 1\” x 1\"<br/>Imprint area: 2.6\" x 0.5\"<br/>Imprint locations: 4 locations<br/>Decorating Methods: Screen Print, 4 Color Process, Laser Engrave",
	  techSpecifications: "mAh: 2200, 2600, 3000<br/> # of Outputs: 1<br/>Output Current: 5V-1000ma<br/> Input Current: 5V-1000ma<br/>Standby Time: 60 days<br/>Battery Type: Grade A, Lithium Ion<br/>Charging Time: 1.5-Hours <br/>Works on iPhones, Androids, Blackberrys and other phones that require a USB charging cord.<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/powerbanks/DSC_2216.jpg",
	  computerSlide2: "../images/products/powerbanks/DSC_2341.jpg",
	  computerSlide3: "../images/products/powerbanks/DSC_2307.jpg",
	  tabletSlide1: "../images/products/powerbanks/DSC_2216.jpg",
	  tabletSlide2: "../images/products/powerbanks/DSC_2341.jpg",
	  tabletSlide3: "../images/products/powerbanks/DSC_2307.jpg",
	  mobileSlide1: "../images/products/powerbanks/DSC_2216.jpg",
	  mobileSlide2: "../images/products/powerbanks/DSC_2341.jpg",
	  mobileSlide3: "../images/products/powerbanks/DSC_2307.jpg",
	},
	{
	  sku: "ACR326",
	  category: "powerbanks",
	  productTitle: "Monroe",
	  productUpperDescription: "",
	  productLowerDescription: "The Monroe power bank is smooth and durable.  It is a great custom power bank that makes you stand out from the crowd. Its cylinder shape fits comfortably in your hand and a laser engraved logo gives your imprint an incredible pop.",
	  printingOptions: "Product Size: 3.625\” x 0.75\” x 0.375\"<br/>Imprint area: 2.15\" x 0.5\"<br/>Imprint locations: 4 locations<br/>Decorating Methods: Screen Print, 4 Color Process, Laser Engrave",
	  techSpecifications: "mAh: 2200, 2600, 3000<br/> # of Outputs: 1<br/>Output Current: 5V-1000ma<br/> Input Current: 5V-1000ma<br/>Standby Time: 60 days<br/>Battery Type: Grade A, Lithium Ion<br/>Charging Time: 1.5-Hours <br/>Works on iPhones, Androids, Blackberrys and other phones that require a USB charging cord.<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/powerbanks/DSC_2161.jpg",
	  computerSlide2: "../images/products/powerbanks/DSC_2301.jpg",
	  computerSlide3: "../images/products/powerbanks/DSC_2336.jpg",
	  computerSlide4: "../images/products/powerbanks/DSC_2299.jpg",
	  tabletSlide1: "../images/products/powerbanks/DSC_2161.jpg",
	  tabletSlide2: "../images/products/powerbanks/DSC_2301.jpg",
	  tabletSlide3: "../images/products/powerbanks/DSC_2336.jpg",
	  tabletSlide4: "../images/products/powerbanks/DSC_2299.jpg",
	  mobileSlide1: "../images/products/powerbanks/DSC_2161.jpg",
	  mobileSlide2: "../images/products/powerbanks/DSC_2301.jpg",
	  mobileSlide3: "../images/products/powerbanks/DSC_2336.jpg",
	  mobileSlide4: "../images/products/powerbanks/DSC_2299.jpg",
	},
	{
	  sku: "ACR327",
	  category: "powerbanks",
	  productTitle: "Lincoln",
	  productUpperDescription: " ",
	  productLowerDescription: "The Lincoln power bank is made from bamboo.  This portable power bank will add to your logo and imprint by giving an eco-friendly voice.  The natural material makes for a great gift.",
	  printingOptions: "Product Size: 4\” x 1\” x 1\"<br/>Imprint area: 2.6\" x 0.5\"<br/>Imprint locations: 4 locations<br/>Decorating Methods: Screen Print, 4 Color Process, Laser Engrave",
	  techSpecifications: "mAh: 2200, 2600, 3000<br/> # of Outputs: 1<br/>Output Current: 5V-1000ma<br/> Input Current: 5V-1000ma<br/>Standby Time: 60 days<br/>Battery Type: Grade A, Lithium Ion<br/>Charging Time: 1.5-Hours <br/>Works on iPhones, Androids, Blackberrys and other phones that require a USB charging cord.<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/powerbanks/WOODPB_1.jpg",
	  computerSlide2: "../images/products/powerbanks/WOODPB_2.jpg",
	  computerSlide3: "../images/products/powerbanks/WOODPB_3.jpg",
	  tabletSlide1: "../images/products/powerbanks/WOODPB_1.jpg",
	  tabletSlide2: "../images/products/powerbanks/WOODPB_2.jpg",
	  tabletSlide3: "../images/products/powerbanks/WOODPB_3.jpg",
	  mobileSlide1: "../images/products/powerbanks/WOODPB_1.jpg",
	  mobileSlide2: "../images/products/powerbanks/WOODPB_2.jpg",
	  mobileSlide3: "../images/products/powerbanks/WOODPB_3.jpg",
	},
	{
	  sku: "ACR328",
	  category: "powerbanks",
	  productTitle: "Truman",
	  productUpperDescription: " ",
	  productLowerDescription: "The Truman power bank has an indicator feature which allows you to see how much time and charge is left on your USB charger.  The power bank is made of metal with chrome accents.  Laser engraving your logo or doing a solid spot color imprint looks fantastic on this portable charger.",
	  printingOptions: "Product Size: 3.75\” x 0.75\” x 0.75\"<br/>Imprint area: 2.25\" x 0.44\"<br/>Imprint locations: 4 locations<br/>Decorating Methods: Screen Print, 4 Color Process, Laser Engrave",
	  techSpecifications: "mAh: 2200, 2600, 3000<br/> # of Outputs: 1<br/>Output Current: 5V-1000ma<br/> Input Current: 5V-1000ma<br/>Standby Time: 60 days<br/>Battery Type: Grade A, Lithium Ion<br/>Charging Time: 1.5-Hours <br/>Works on iPhones, Androids, Blackberrys and other phones that require a USB charging cord.<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/powerbanks/TRUMAN_2.jpeg",
	  computerSlide2: "../images/products/powerbanks/TRUMAN_1.jpeg",
	  tabletSlide1: "../images/products/powerbanks/TRUMAN_2.jpeg",
	  tabletSlide2: "../images/products/powerbanks/TRUMAN_1.jpeg",
	  mobileSlide1: "../images/products/powerbanks/TRUMAN_2.jpeg",
	  mobileSlide2: "../images/products/powerbanks/TRUMAN_1.jpeg",
	},
	{
	  sku: "ACR329",
	  category: "selfie",
	  productTitle: "Da Vinci",
	  productUpperDescription: " ",
	  productLowerDescription: "The Da Vinci is a wired selfie stick that extends the pole an additional 30” so you can capture the moment wherever you are.  Simply plug in your phone, secure it on the spring loaded case and use the easy access photo button on the handle to take the picture.  Brand the selfie stick however you would like.  Put your logo above the handle or imprint on the phone case.",
	  printingOptions: "Product Size: 12.25\” extends to 42\”<br/>Imprint Size: 1\" x 1.5\"<br/>Imprint locations: 2 locations<br/>Decorating Methods: Screen Print",
	  techSpecifications: "Wired Selfie Stick<br/>Materials Use: Plastic, Metal, Rubber<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/products/selfie/SELFIE_PLATE_BACK.jpg",
	  tabletSlide1: "../images/products/selfie/SELFIE_PLATE_BACK.jpg",
	  mobileSlide1: "../images/products/selfie/SELFIE_PLATE_BACK.jpg",
	},
	{
	  sku: "ACR330",
	  category: "speakers",
	  productTitle: "Presley",
	  productUpperDescription: " ",
	  productLowerDescription: "Power your music with the Presley Bluetooth Speaker! Quality sound in a small form factor that plays your music or other audio from a Bluetooth enabled device or via the 3.5mm audio input, making it compatible with just about anything that plays music. Perfect for anyone that travels and is on-the-go or it can simply sit at a desk in an office setting.",
	  printingOptions: "Product Size: 2.25\” x 15\” x 4.25\"<br/>Imprint Size: 0.63\" x 1.25\"<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print, 4 Color Process",
	  techSpecifications: "Bluetooth Technology<br/>3.5mm Audio Cable Included<br/>Charging Cable Included<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/speakers/DP-PowerBanks-Madison.jpg",
	  computerSlide2: "../images/speakers/DP-PowerBanks-Madison2.jpg",
	  tabletSlide1: "../images/speakers/DP-PowerBanks-Madison.jpg",
	  tabletSlide2: "../images/speakers/DP-PowerBanks-Madison2.jpg",
	  mobileSlide1: "../images/speakers/DP-PowerBanks-Madison.jpg",
	  mobileSlide2: "../images/speakers/DP-PowerBanks-Madison2.jpg",
	},
	{
	  sku: "ACR331",
	  category: "speakers",
	  productTitle: "Bach",
	  productUpperDescription: " ",
	  productLowerDescription: "Bach Bluetooth Speaker allows you to stream audio from your Bluetooth enabled devices anywhere. Play music, movies, and mobile audio as they were originally created in the studio, all within the palm of your hand. Take your music with you on the go, or keep in an office or home to enjoy quality sound.",
	  printingOptions: "Product Size: 2.0\” x 2.36\” x 2.36\"<br/>Imprint Size: 0.9\" x 0.9\"<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print, 2 Color Process",
	  techSpecifications: "Bluetooth Technology<br/>3.5mm Audio Cable Included<br/>Charging Cable Included<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/speakers/DP-PowerBanks-VanBuren.jpg",
	  tabletSlide1: "../images/speakers/DP-PowerBanks-VanBuren.jpg",
	  mobileSlide1: "../images/speakers/DP-PowerBanks-VanBuren.jpg",

	},
	{
	  sku: "ACR332",
	  category: "speakers",
	  productTitle: "Hendrix",
	  productUpperDescription: " ",
	  productLowerDescription: "Connect any Bluetooth device to the Hendrix and you can’t go wrong.  Small and compact, this speaker gives amazing sound quality and is among our most popular speakers.",
	  printingOptions: "Product Size: 2.0\” x 2.36\” x 2.36\"<br/>Imprint Size: 0.9\" x 0.9\"<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print, 2 Color Process",
	  techSpecifications: "Bluetooth Technology<br/>3.5mm Audio Cable Included<br/>Charging Cable Included<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/speakers/DP-PowerBanks-Lincoln.jpg",
	  tabletSlide1: "../images/speakers/DP-PowerBanks-Lincoln.jpg",
	  mobileSlide1: "../images/speakers/DP-PowerBanks-Lincoln.jpg",
	},
	{
	  sku: "ACR333",
	  category: "speakers",
	  productTitle: "Lennon",
	  productUpperDescription: " ",
	  productLowerDescription: "Power your music with Lennon! Quality sound in a small form factor that plays your music or other audio from a Bluetooth enabled device or via the 3.5mm audio input, making it compatible with just about anything that plays music. Rechargeable speaker is perfect for traveling or in an office setting.",
	  printingOptions: "Product Size: 1.56\” x 2.125\” x 2.125\"<br/>Imprint Size: 1.13\" x 1.13\"<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print, 2 Color Process",
	  techSpecifications: "Bluetooth Technology<br/>3.5mm Audio Cable Included<br/>Charging Cable Included<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/speakers/DP-PowerBanks-Johnson.jpg",
	  computerSlide2: "../images/speakers/DP-PowerBanks-Johnson2.jpg",
	  tabletSlide1: "../images/speakers/DP-PowerBanks-Johnson.jpg",
	  tabletSlide2: "../images/speakers/DP-PowerBanks-Johnson2.jpg",
	  mobileSlide1: "../images/speakers/DP-PowerBanks-Johnson.jpg",
	  mobileSlide2: "../images/speakers/DP-PowerBanks-Johnson2.jpg",
	},
	{
	  sku: "ACR334",
	  category: "speakers",
	  productTitle: "Cash",
	  productUpperDescription: " ",
	  productLowerDescription: "Rechargeable speaker connects to your Bluetooth enabled device within 10 meters of the speaker. Perfect for travelling, or in an office to deliver the music that your iPhone, iPad, Android OS device, or other Bluetooth enabled device is meant to.",
	  printingOptions: "Product Size: 2.25\” x 1.5\”<br/>Imprint Size: 1\" x 1\"<br/>Imprint locations: 1 locations<br/>Decorating Methods: Screen Print, 2 Color Process",
	  techSpecifications: "Bluetooth Technology<br/>3.5mm Audio Cable Included<br/>Charging Cable Included<br/>Warranty: 100% Customer Satisfaction Guarantee, Lifetime Warranty",
	  computerSlide1: "../images/speakers/DP-PowerBanks-Truman.jpg",
	  tabletSlide1: "../images/speakers/DP-PowerBanks-Truman.jpg",
	  mobileSlide1: "../images/speakers/DP-PowerBanks-Truman.jpg",
	}
]